version: "1.0"
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./vols/.env:/backend/.env
      - ./vols/sql_app.db:/backend/sql_app.db

  frontend:
    build: ./frontend
    ports:
      - 5173:80
